name: Deploy

on:
    push:
        branches: [ master ]
        
jobs:
    deploy:
        name: Deploy    
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Install dependencies
          run: npm install
        - name: Vue Build
          run: npm run build
        - name: Upload to server
          uses: appleboy/scp-action@v0.1.1
          with:
            host: ${{ secrets.SECRET_HOST }}
            username: ${{ secrets.SECRET_USER }}
            key: ${{ secrets.SECRET_RSA }}
            port: ${{ secrets.SECRET_PORT }}
            source: "dist/"
            target: ${{ secrets.SECRET_PATH }}
            strip_components: 1